### ISSUE TITLE
Microstack initialization problem

### ISSUE THREAD

**Issue by dominiktopyla** [canonical-web-and-design/microstack.run#136]
## Summary

I have installed osm charmed and try to set K8s cluster (https://osm.etsi.org/docs/user-guide/15-k8s-installation.html#installation-method-2-local-development-environment ) and I need microstack, connect openstack.
I followed tutorial: https://microstack.run/docs/single-node
and faced errors during initailization 

## Process

sudo snap install microstack --devmode --beta
sudo microstack init --auto --control

## Current and expected result

I expected successful initialization.

## Screenshot

**dominik@dominik:~$ sudo snap install microstack --devmode --beta
[sudo] password for dominik: 
microstack (beta) ussuri from Canonical?? installed
dominik@dominik:~$ snap list microstack
Name        Version  Rev  Tracking     Publisher   Notes
microstack  ussuri   241  latest/beta  canonical??  devmode
dominik@dominik:~$ sudo microstack init --auto --control
2021-11-09 22:49:28,819 - microstack_init - INFO - Configuring clustering ...
2021-11-09 22:49:29,105 - microstack_init - INFO - Setting up as a control node.
2021-11-09 22:49:34,510 - microstack_init - INFO - Generating TLS Certificate and Key
2021-11-09 22:49:36,329 - microstack_init - INFO - Configuring networking ...
2021-11-09 22:49:50,817 - microstack_init - INFO - Opening horizon dashboard up to *
2021-11-09 22:49:52,382 - microstack_init - INFO - Waiting for RabbitMQ to start ...
Waiting for 10.140.0.133:5672
2021-11-09 22:50:02,680 - microstack_init - INFO - RabbitMQ started!
2021-11-09 22:50:02,680 - microstack_init - INFO - Configuring RabbitMQ ...
2021-11-09 22:50:04,368 - microstack_init - INFO - RabbitMQ Configured!
2021-11-09 22:50:04,405 - microstack_init - INFO - Waiting for MySQL server to start ...
Waiting for 10.140.0.133:3306
2021-11-09 22:50:12,559 - microstack_init - INFO - Mysql server started! Creating databases ...
Traceback (most recent call last):
  File "/snap/microstack/241/bin/microstack", line 11, in <module>
    load_entry_point('microstack==0.0.1', 'console_scripts', 'microstack')()
  File "/snap/microstack/241/lib/python3.8/site-packages/microstack/main.py", line 44, in main
    cmd()
  File "/snap/microstack/241/lib/python3.8/site-packages/init/main.py", line 60, in wrapper
    return func(*args, **kwargs)
  File "/snap/microstack/241/lib/python3.8/site-packages/init/main.py", line 228, in init
    question.ask()
  File "/snap/microstack/241/lib/python3.8/site-packages/init/questions/question.py", line 210, in ask
    self.yes(awr)
  File "/snap/microstack/241/lib/python3.8/site-packages/init/questions/__init__.py", line 476, in yes
    enable('nginx')
  File "/snap/microstack/241/lib/python3.8/site-packages/init/shell.py", line 162, in enable
    check('snapctl', 'start', 'microstack.{}'.format(service), '--enable')
  File "/snap/microstack/241/lib/python3.8/site-packages/init/shell.py", line 69, in check
    raise subprocess.CalledProcessError(proc.returncode, " ".join(args))
subprocess.CalledProcessError: Command 'snapctl start microstack.nginx --enable' returned non-zero exit status 1.**

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by carkod** [comment]
Hi @dominiktopyla, thanks for reporting this, but this is the repo for the microstack.run website, you may not be able to find much help here. Check out our [Microstack tutorials](https://ubuntu.com/tutorials/microstack-get-started?&_ga=2.20771323.2132059613.1636649545-747945304.1636649544#1-overview), or if you need further help, please take a look at https://discourse.ubuntu.com/t/single-node/21427/3 the Microstack team may be able to help you further over there. Else you can still try [Stackoverflow](https://stackoverflow.com/questions/tagged/microstack)

**Comment by sowasred2012** [comment]
Closing for inactivity, reopen if needed.

**Comment by isaacpina** [comment]
Hello @dominiktopyla! Were you able to solve this issue?

**Comment by anthonyKiggundu** [comment]
This bug was closed but the issue still exists unfortunately. It would be nice if someone really took a look please.
