### ISSUE TITLE
microstack launch error

### ISSUE THREAD

**Issue by ehcpdeveloper** [canonical-web-and-design/microstack.run#178]
```
root@controller:~# microstack launch cirros
Creating local "microstack" ssh key at /home/root/snap/microstack/common/.ssh/id_microstack
mkdir: cannot create directory '/home/root': Permission denied
Traceback (most recent call last):
  File "/snap/microstack/245/bin/microstack", line 11, in <module>
    load_entry_point('microstack==0.0.1', 'console_scripts', 'microstack')()
  File "/snap/microstack/245/lib/python3.8/site-packages/microstack/main.py", line 44, in main
    cmd()
  File "/snap/microstack/245/lib/python3.8/site-packages/launch/main.py", line 232, in main
    return launch(name, args)
  File "/snap/microstack/245/lib/python3.8/site-packages/launch/main.py", line 166, in launch
    key_path = check_keypair()
  File "/snap/microstack/245/lib/python3.8/site-packages/launch/main.py", line 73, in check_keypair
    check('mkdir', '-p', key_dir)
  File "/snap/microstack/245/lib/python3.8/site-packages/launch/main.py", line 17, in check
    return subprocess.check_call(args, env=os.environ)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('mkdir', '-p', '/home/root/snap/microstack/common/.ssh')' returned non-zero exit status 1.
```

After installation of microstack, very first command.

**Comment by anthonydillon** [comment]
Hi @ehcpdeveloper, sorry but this repo and issue list are for the website and its content. Please report this issue on the microk8s project issue list: https://github.com/canonical/microk8s
