### ISSUE TITLE
Test instance in ERROR after brand new installation on Ubuntu 20.04 on R710 dell server

### ISSUE THREAD

**Issue by m5santovito** [canonical-web-and-design/microstack.run#180]
## Summary
The test instance is created but is in ERROR status after a brand new installation of microstack Ussuri

## Process
I've got a R710 Dell server runnign a Ubuntu 20.04.4 version
microstack just installed according to microstack.run instructions. 

## Current and expected result

I've run the command:
microstack launch cirros --name test
but I was unable to ssh into it. Listing the servers I'm keeping on getting always the same results:
+--------------------------------------+------+--------+----------+--------+---------+
| ID                                   | Name | Status | Networks | Image  | Flavor  |
+--------------------------------------+------+--------+----------+--------+---------+
| 78909dd6-f176-418d-911a-7967fcebd474 | test | ERROR  |          | cirros | m1.tiny |
+--------------------------------------+------+--------+----------+--------+---------+
Checking the microstack snap services (systemctl status snap.microstack.*) I can see some strange messages:

-----------------------
● snap.microstack.libvirtd.service - Service for snap application microstack.libvirtd
     Loaded: loaded (/etc/systemd/system/snap.microstack.libvirtd.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-04-06 17:00:57 CEST; 45min ago
   Main PID: 1010932 (libvirtd)
      Tasks: 17 (limit: 154590)
     Memory: 14.5M
     CGroup: /system.slice/snap.microstack.libvirtd.service
             └─1010932 /snap/microstack/245/usr/sbin/libvirtd --pid /var/snap/microstack/245/libvirt.pid --listen

Apr 06 17:00:57 server1.dacsystem-office.ch systemd[1]: Started Service for snap application microstack.libvirtd.
Apr 06 17:01:26 server1.dacsystem-office.ch libvirtd[1010932]: libvirt version: 6.0.0
Apr 06 17:01:26 server1.dacsystem-office.ch libvirtd[1010932]: hostname: server1.dacsystem-office.ch
Apr 06 17:01:26 server1.dacsystem-office.ch libvirtd[1010932]: End of file while reading data: Input/output error
Apr 06 17:01:35 server1.dacsystem-office.ch libvirtd[1010932]: invalid argument: KVM is not supported by '/snap/microstack/245/usr/bin/qemu-system-aarch64' on this host
-----------------------

-----------------------
snap.microstack.nova-conductor.service - Service for snap application microstack.nova-conductor
     Loaded: loaded (/etc/systemd/system/snap.microstack.nova-conductor.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-04-06 16:55:55 CEST; 52min ago
   Main PID: 1005308 (python3)
      Tasks: 5 (limit: 154590)
     Memory: 269.0M
     CGroup: /system.slice/snap.microstack.nova-conductor.service
             ├─1005308 python3 /snap/microstack/245/bin/nova-conductor --config-file=/snap/microstack/245/etc/nova/nova.conf --config-dir=/var/snap/microstack/common/etc/nova/nova.conf.d
             ├─1006107 python3 /snap/microstack/245/bin/nova-conductor --config-file=/snap/microstack/245/etc/nova/nova.conf --config-dir=/var/snap/microstack/common/etc/nova/nova.conf.d
             ├─1006108 python3 /snap/microstack/245/bin/nova-conductor --config-file=/snap/microstack/245/etc/nova/nova.conf --config-dir=/var/snap/microstack/common/etc/nova/nova.conf.d
             ├─1006109 python3 /snap/microstack/245/bin/nova-conductor --config-file=/snap/microstack/245/etc/nova/nova.conf --config-dir=/var/snap/microstack/common/etc/nova/nova.conf.d
             └─1006110 python3 /snap/microstack/245/bin/nova-conductor --config-file=/snap/microstack/245/etc/nova/nova.conf --config-dir=/var/snap/microstack/common/etc/nova/nova.conf.d

Apr 06 16:55:55 server1.dacsystem-office.ch systemd[1]: Started Service for snap application microstack.nova-conductor.
Apr 06 16:56:00 server1.dacsystem-office.ch nova-conductor[1005308]: 2022-04-06 16:56:00.250 1005308 INFO oslo_service.service [-] Starting 4 workers
Apr 06 16:56:00 server1.dacsystem-office.ch nova-conductor[1006107]: 2022-04-06 16:56:00.258 1006107 INFO nova.service [-] Starting conductor node (version 21.1.1)
Apr 06 16:56:00 server1.dacsystem-office.ch nova-conductor[1006108]: 2022-04-06 16:56:00.258 1006108 INFO nova.service [-] Starting conductor node (version 21.1.1)
Apr 06 16:56:00 server1.dacsystem-office.ch nova-conductor[1006109]: 2022-04-06 16:56:00.260 1006109 INFO nova.service [-] Starting conductor node (version 21.1.1)
Apr 06 16:56:00 server1.dacsystem-office.ch nova-conductor[1006110]: 2022-04-06 16:56:00.261 1006110 INFO nova.service [-] Starting conductor node (version 21.1.1)
Apr 06 16:56:00 server1.dacsystem-office.ch nova-conductor[1005308]: 2022-04-06 16:56:00.284 1005308 WARNING oslo_config.cfg [-] Deprecated: Option "keymap" from group "spice" is deprecated for removal (
                                                                     Configuring this option forces QEMU to do keymap conversions. These conversions
                                                                     are lossy and can result in significant issues for users of non en-US
                                                                     keyboards. Refer to bug #1682020 for more information.).  Its value may be silently ignored in the future.
Apr 06 17:09:01 server1.dacsystem-office.ch nova-conductor[1006107]: 2022-04-06 17:09:01.289 1006107 ERROR nova.scheduler.utils [req-ff97f343-29c1-4d44-ac9c-97ba8d70eb07 60edbb2732484af8a0ef87571699e189 754789b5f0c74f1d818cb76a93babc1b - default default] [instance: 78909dd6-f176-418d-911a-7967fcebd474] Error from last host: dacserver1.dacsystem-office.ch (node server1.dacsystem-office.ch): ['Traceback (most recent call last):\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 2374, in _build_and_run_instance\n    self.driver.spawn(context, instance, image_meta,\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/virt/libvirt/driver.py", line 3673, in spawn\n    xml = self._get_guest_xml(context, instance, network_info,\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/virt/libvirt/driver.py", line 6350, in _get_guest_xml\n    network_info_str = str(network_info)\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/model.py", line 601, in __str__\n    return self._sync_wrapper(fn, *args, **kwargs)\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/model.py", line 584, in _sync_wrapper\n    self.wait()\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/model.py", line 616, in wait\n    self[:] = self._gt.wait()\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/greenthread.py", line 181, in wait\n    return self._exit_event.wait()\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/event.py", line 125, in wait\n    result = hub.switch()\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 298, in switch\n    return self.greenlet.switch()\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/greenthread.py", line 221, in main\n    result = function(*args, **kwargs)\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/utils.py", line 670, in context_wrapper\n    return func(*args, **kwargs)\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 1749, in _allocate_network_async\n    six.reraise(*exc_info)\n', '  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise\n    raise value\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 1727, in _allocate_network_async\n    nwinfo = self.network_api.allocate_for_instance(\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 1109, in allocate_for_instance\n    created_port_ids = self._update_ports_for_instance(\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 1241, in _update_ports_for_instance\n    vif.destroy()\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/oslo_utils/excutils.py", line 220, in __exit__\n    self.force_reraise()\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/oslo_utils/excutils.py", line 196, in force_reraise\n    six.reraise(self.type_, self.value, self.tb)\n', '  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise\n    raise value\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 1210, in _update_ports_for_instance\n    updated_port = self._update_port(\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 585, in _update_port\n    _ensure_no_port_binding_failure(port)\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 299, in _ensure_no_port_binding_failure\n    raise exception.PortBindingFailed(port_id=port[\'id\'])\n', 'nova.exception.PortBindingFailed: Binding failed for port 48331784-f146-4b1e-bd9f-70b1f1cb6e37, please check neutron logs for more information.\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 2197, in _do_build_and_run_instance\n    self._build_and_run_instance(context, instance, image,\n', '  File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 2477, in _build_and_run_instance\n    raise exception.RescheduledException(\n', 'nova.exception.RescheduledException: Build of instance 78909dd6-f176-418d-911a-7967fcebd474 was re-scheduled: Binding failed for port 48331784-f146-4b1e-bd9f-70b1f1cb6e37, please check neutron logs for more information.\n']

Apr 06 17:09:01 server1.dacsystem-office.ch nova-conductor[1006107]: 2022-04-06 17:09:01.292 1006107 WARNING nova.scheduler.utils [req-ff97f343-29c1-4d44-ac9c-97ba8d70eb07 60edbb2732484af8a0ef87571699e189 754789b5f0c74f1d818c>
Apr 06 17:09:01 server1.dacsystem-office.ch nova-conductor[1006107]: 2022-04-06 17:09:01.292 1006107 WARNING nova.scheduler.utils [req-ff97f343-29c1-4d44-ac9c-97ba8d70eb07 60edbb2732484af8a0ef87571699e189 754789b5f0c74f1d818c>

------------------------------
● snap.microstack.ovn-ovsdb-server-sb.service - Service for snap application microstack.ovn-ovsdb-server-sb
     Loaded: loaded (/etc/systemd/system/snap.microstack.ovn-ovsdb-server-sb.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-04-06 16:53:13 CEST; 58min ago
   Main PID: 997452 (monitor)
      Tasks: 2 (limit: 154590)
     Memory: 6.8M
     CGroup: /system.slice/snap.microstack.ovn-ovsdb-server-sb.service
             ├─997452 ovsdb-server: monitoring pid 997453 (healthy)
             └─997453 ovsdb-server -vconsole:off -vfile:info --log-file=/var/snap/microstack/common/log/ovn/ovsdb-server-sb.log --remote=punix:/var/snap/microstack/common/run/ovn/ovnsb_db.sock --pidfile=/var/snap/microstack/c>

Apr 06 17:49:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00239|ovsdb_jsonrpc_server|ERR|Dropped 23 log messages in last 58 seconds (most recently, 3 seconds ago) due to excessive rate
Apr 06 17:49:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00240|ovsdb_jsonrpc_server|ERR|ptcp:6642:0.0.0.0: listen failed: Address already in use
Apr 06 17:50:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00241|socket_util|ERR|Dropped 23 log messages in last 58 seconds (most recently, 3 seconds ago) due to excessive rate
Apr 06 17:50:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00242|socket_util|ERR|6642:0.0.0.0: bind: Address already in use
Apr 06 17:50:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00243|ovsdb_jsonrpc_server|ERR|Dropped 23 log messages in last 58 seconds (most recently, 3 seconds ago) due to excessive rate
Apr 06 17:50:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00244|ovsdb_jsonrpc_server|ERR|ptcp:6642:0.0.0.0: listen failed: Address already in use
Apr 06 17:51:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00245|socket_util|ERR|Dropped 23 log messages in last 58 seconds (most recently, 3 seconds ago) due to excessive rate
Apr 06 17:51:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00246|socket_util|ERR|6642:0.0.0.0: bind: Address already in use
Apr 06 17:51:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00247|ovsdb_jsonrpc_server|ERR|Dropped 23 log messages in last 58 seconds (most recently, 3 seconds ago) due to excessive rate
Apr 06 17:51:14 server1.dacsystem-office.ch ovsdb-server[997453]: ovs|00248|ovsdb_jsonrpc_server|ERR|ptcp:6642:0.0.0.0: listen failed: Address already in use

-------------------------------------------

-----------------------
 snap.microstack.nova-compute.service - Service for snap application microstack.nova-compute
     Loaded: loaded (/etc/systemd/system/snap.microstack.nova-compute.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-04-06 17:01:27 CEST; 50min ago
   Main PID: 1011073 (python3)
      Tasks: 24 (limit: 154590)
     Memory: 158.3M
     CGroup: /system.slice/snap.microstack.nova-compute.service
             ├─1011073 python3 /snap/microstack/245/bin/nova-compute --config-file=/snap/microstack/245/etc/nova/nova.conf --config-dir=/var/snap/microstack/common/etc/nova/nova.conf.d
             └─1012220 python3 /snap/microstack/245/bin/privsep-helper --config-file /snap/microstack/245/etc/nova/nova.conf --config-dir /var/snap/microstack/common/etc/nova/nova.conf.d --privsep_context nova.privsep.sys_adm>

Apr 06 17:09:00 server1.dacsystem-office.ch nova-compute[1011073]: 2022-04-06 17:09:00.697 1011073 INFO nova.compute.manager [req-ff97f343-29c1-4d44-ac9c-97ba8d70eb07 60edbb2732484af8a0ef87571699e189 754789b5f0c74f1d818cb76a9>
Apr 06 17:09:00 server1.dacsystem-office.ch nova-compute[1011073]: 2022-04-06 17:09:00.755 1011073 INFO nova.compute.manager [-] [instance: 78909dd6-f176-418d-911a-7967fcebd474] Took 0.06 seconds to deallocate network for ins>
Apr 06 17:09:00 server1.dacsystem-office.ch nova-compute[1011073]: 
Apr 06 17:09:00 server1.dacsystem-office.ch nova-compute[1011073]: 2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [req-ff97f343-29c1-4d44-ac9c-97ba8d70eb07 60edbb2732484af8a0ef87571699e189 754789b5f0c74f1d818cb76a93babc1b - default default] [instance: 78909dd6-f176-418d-911a-7967fcebd474] Failed to build and run instance: nova.exception.PortBindingFailed: Binding failed for port 48331784-f146-4b1e-bd9f-70b1f1cb6e37, please check neutron logs for more information.
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474] Traceback (most recent call last):
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 2374, in _build_and_run_instance
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     self.driver.spawn(context, instance, image_meta,
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/virt/libvirt/driver.py", line 3673, in spawn
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     xml = self._get_guest_xml(context, instance, network_info,
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/virt/libvirt/driver.py", line 6350, in _get_guest_xml
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     network_info_str = str(network_info)
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/model.py", line 601, in __str__
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     return self._sync_wrapper(fn, *args, **kwargs)
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/model.py", line 584, in _sync_wrapper
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     self.wait()
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/model.py", line 616, in wait
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     self[:] = self._gt.wait()
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/greenthread.py", line 181, in wait
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     return self._exit_event.wait()
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/event.py", line 125, in wait
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     result = hub.switch()
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 298, in switch
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     return self.greenlet.switch()
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/eventlet/greenthread.py", line 221, in main
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     result = function(*args, **kwargs)
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/utils.py", line 670, in context_wrapper
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     return func(*args, **kwargs)
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 1749, in _allocate_network_async
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     six.reraise(*exc_info)
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     raise value
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/compute/manager.py", line 1727, in _allocate_network_async
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     nwinfo = self.network_api.allocate_for_instance(
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 1109, in allocate_for_instance
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     created_port_ids = self._update_ports_for_instance(
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 1241, in _update_ports_for_instance
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     vif.destroy()
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/oslo_utils/excutils.py", line 220, in __exit__
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     self.force_reraise()
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     six.reraise(self.type_, self.value, self.tb)
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     raise value
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 1210, in _update_ports_for_instance
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     updated_port = self._update_port(
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 585, in _update_port
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     _ensure_no_port_binding_failure(port)
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]   File "/snap/microstack/245/lib/python3.8/site-packages/nova/network/neutron.py", line 299, in _ensure_no_port_binding_failure
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]     raise exception.PortBindingFailed(port_id=port['id'])
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474] nova.exception.PortBindingFailed: Binding failed for port 48331784-f146-4b1e-bd9f-70b1f1cb6e37, please check neutron logs for more information.
                                                                   2022-04-06 17:09:00.878 1011073 ERROR nova.compute.manager [instance: 78909dd6-f176-418d-911a-7967fcebd474]
-------------------------------------------------------

**Comment by cristinadresch** [comment]
@m5santovito thanks for opening this, but could you please open the issue on discourse? This github repo is only for the website, you will get a quicker response there https://discourse.ubuntu.com/c/microstack/58

**Comment by carkod** [comment]
@m5santovito there should be a link at the bottom "Help improve this documentation", can you click on that and post this question in the corresponding discourse topic? Thank you.
